Nc news 12
AdamEth98/be-nc-news pull request #11
Opened 2022-07-06 15:37 UTC by AdamEth98

2022-07-06 15:50 UTC, emilyb93 requested changes

2022-07-06 15:50 UTC, emilyb93 commented on __tests__/index.test.js
> +          expect(Object.keys(body).length).toBe(0);
We could also do this as `.toEqual({})`

2022-07-06 15:50 UTC, emilyb93 commented on __tests__/index.test.js
> +          return db.query("SELECT * from comments WHERE comment_id = 1");
This should be handled as an api request and not just a direct query. What kind of behaviour should a client get if they try to delete a comment which doesnt exist/has been deleted?

2022-07-07 09:23 UTC, Angaca approved these changes
Nice, good to go!

2022-07-07 09:34 UTC, merged